config/routes.rb
ChouetteIhm::Application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations', :invitations => 'users/invitations',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  devise_scope :user do
    authenticated :user do
      root :to => 'referentials#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      get '/additionnal_fields', to: 'users#additionnal_fields'
      post '/save_additionnal_fields', to: 'users#save_additionnal_fields'
    end
    
  end

  namespace :api do
    namespace :v1 do
      resources :time_tables, :only => [:index, :show]
      resources :connection_links, :only => [:index, :show]
      resources :companies, :only => [:index, :show]
      resources :networks, :only => [:index, :show]
      resources :stop_areas, :only => [:index, :show]
      resources :group_of_lines, :only => [:index, :show]
      resources :access_points, :only => [:index, :show]
      resources :access_links, :only => [:index, :show]
      resources :lines, :only => [:index, :show] do
        resources :journey_patterns, :only => [:index, :show]
        resources :routes, :only => [:index, :show] do
          resources :vehicle_journeys, :only => [:index, :show]
          resources :journey_patterns, :only => [:index, :show]
          resources :stop_areas, :only => [:index, :show]
        end
      end
      resources :routes, :only => :show
      resources :journey_patterns, :only => :show
      resources :vehicle_journeys, :only => :show
    end
  end

  resource :organisation, :only => [:show, :edit, :update] do
    resources :users
    get '/role/edit/:id', to: 'users#role_edit', as: 'user_role_edit'
    patch '/role/update/:id', to: 'users#role_update', as: 'user_role_update'
    resources :rule_parameter_sets
  end

  resources :referentials do
    resources :api_keys
    resources :autocomplete_stop_areas
    resources :autocomplete_time_tables
    resources :autocomplete_route_sections
    resources :autocomplete_timebands
    resources :group_of_lines do
      collection do
        get 'name_filter'
      end
    end

    resources :networks

    resources :lines do
      delete :index, on: :collection, action: :delete_all
      collection do
        get 'name_filter'
      end
      resources :routes do
        member do
          get 'edit_boarding_alighting'
          put 'save_boarding_alighting'
        end
        resources :journey_patterns do
          member do
            get 'new_vehicle_journey'
          end
          resource :route_sections_selector, path: 'sections' do
            post 'selection'
          end
        end
        resources :vehicle_journeys, :vehicle_journey_frequencies do
          get 'select_journey_pattern', :on => :member
          resources :vehicle_translations
          resources :time_tables
        end
        resources :vehicle_journey_imports
        resources :vehicle_journey_exports
      end
    end

    resources :import_tasks, :only => [:new, :create]
    resources :imports, :only => [:index, :show, :destroy] do
      member do
        get "imported_file"
        get "rule_parameter_set"
        get "compliance_check"
        get 'progress'
        get 'export', defaults: { format: 'zip' }
      end
    end

    resources :export_tasks, :only => [:new, :create] do
      collection do
        get 'references'
      end
    end

    resources :exports, :only => [:index, :show, :destroy]  do
      member do
        get "exported_file"
        get "compliance_check"
        get 'progress'
        get 'export', defaults: { format: 'zip' }
      end
    end

    resources :compliance_check_tasks, :only => [:new, :create] do
      collection do
        get 'references'
      end
    end

    resources :compliance_checks, :only => [:index, :show, :destroy] do
      member do
        get 'export', defaults: { format: 'zip' }
        get 'report'
        get 'progress'
        get 'rule_parameter_set'
        get 'download_validation'
      end
      collection do
        get 'references'
      end
    end

    resources :companies

    resources :time_tables do
      collection do
        get :tags
      end
      member do
        get 'duplicate'
      end
      resources :time_table_dates
      resources :time_table_periods
      resources :time_table_combinations
    end

    resources :timebands

    resources :access_points do
       resources :access_links
    end

    resources :stop_areas do
      resources :access_points do
        resources :access_links
      end
      resources :stop_area_copies
      resources :stop_area_routing_lines
      member do
        get 'add_children'
        get 'select_parent'
        get 'add_routing_lines'
        get 'add_routing_stops'
        get 'access_links'
      end
      collection do
        put 'default_geometry'
      end
    end

    resources :connection_links do
      resources :stop_areas
      member do
        get 'select_areas'
      end
    end
    resources :clean_ups

    resources :route_sections do
      collection  do
        get 'create_to_edit'
      end
    end
  end
  root :to => "referentials#index"

  get '/statistics', :to => 'statistics#index'
  get '/statistics/export', :to => 'statistics#export'

  get '/help/(*slug)' => 'help#show'

  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#server_error'
  get '/500', :to => 'errors#server_error'

end

app/models/referential.rb
# -*- coding: utf-8 -*-
class Referential < ActiveRecord::Base
  include DataFormatEnumerations

  validates_presence_of :name
  validates_presence_of :prefix
  validates_presence_of :time_zone
  validates_presence_of :upper_corner
  validates_presence_of :lower_corner
  validates_uniqueness_of :name, scope: :organisation_id
  validates_format_of :prefix, :with => %r{\A[0-9a-zA-Z_]+\Z}
  validates_format_of :upper_corner, :with => %r{\A-?[0-9]+\.?[0-9]*\,-?[0-9]+\.?[0-9]*\Z}
  validates_format_of :lower_corner, :with => %r{\A-?[0-9]+\.?[0-9]*\,-?[0-9]+\.?[0-9]*\Z}
  validate :slug_excluded_values

  attr_accessor :upper_corner
  attr_accessor :lower_corner

  has_one :user
  has_many :api_keys, :class_name => 'Api::V1::ApiKey', :dependent => :destroy

  belongs_to :organisation
  validates_presence_of :organisation

  after_save :set_slug

  def slug_excluded_values
    if slug.present?
      if slug.start_with? "pg_"
        errors.add(:slug,I18n.t("referentials.errors.pg_excluded"))
      end
      if slug == 'public'
        errors.add(:slug,I18n.t("referentials.errors.public_excluded"))
      end
      if slug == self.class.connection_config[:username]
        errors.add(:slug,I18n.t("referentials.errors.user_excluded", :user => slug))
      end
    end
  end

  def viewbox_left_top_right_bottom
    [  lower_corner.lng, upper_corner.lat, upper_corner.lng, lower_corner.lat ].join(',')
  end

  def human_attribute_name(*args)
    self.class.human_attribute_name(*args)
  end

  def lines
    Chouette::Line.all
  end

  def networks
    Chouette::Network.all
  end

  def group_of_lines
    Chouette::GroupOfLine.all
  end

  def companies
    Chouette::Company.all
  end

  def stop_areas
    Chouette::StopArea.all
  end

  def access_points
    Chouette::AccessPoint.all
  end

  def access_links
    Chouette::AccessLink.all
  end

  def time_tables
    Chouette::TimeTable.all
  end

  def timebands
    Chouette::Timeband.all
  end

  def connection_links
    Chouette::ConnectionLink.all
  end

  def vehicle_journeys
    Chouette::VehicleJourney.all
  end

  def vehicle_journey_frequencies
    Chouette::VehicleJourneyFrequency.all
  end

  def route_sections
    Chouette::RouteSection.all
  end

  def time_zone_tzinfo
    time_zone = ActiveSupport::TimeZone.new(self.time_zone)
    time_zone ? time_zone.tzinfo.name : self.time_zone
  end

  after_initialize :define_default_attributes

  def define_default_attributes
    self.time_zone ||= Time.zone.name
  end

  def switch
    raise "Referential not created" if new_record?
    Apartment::Tenant.switch!(self.slug)
    self
  end

  def self.available_srids
    [
      [ "RGF 93 Lambert 93 (2154)", 2154 ],
      [ "RGF93 CC42 (zone 1) (3942)", 3942 ],
      [ "RGF93 CC43 (zone 2) (3943)", 3943 ],
      [ "RGF93 CC44 (zone 3) (3944)", 3944 ],
      [ "RGF93 CC45 (zone 4) (3945)", 3945 ],
      [ "RGF93 CC46 (zone 5) (3946)", 3946 ],
      [ "RGF93 CC47 (zone 6) (3947)", 3947 ],
      [ "RGF93 CC48 (zone 7) (3948)", 3948 ],
      [ "RGF93 CC49 (zone 8) (3949)", 3949 ],
      [ "RGF93 CC50 (zone 9) (3950)", 3950 ],
      [ "NTF Lambert Zone 1 Nord (27561)", 27561 ],
      [ "NTF Lambert Zone 2 Centre (27562)", 27562 ],
      [ "NTF Lambert Zone 3 Sud (27563)", 27563 ],
      [ "NTF Lambert Zone 4 Corse (27564)", 27564 ],
      [ "NTF Lambert 1 Carto (27571)", 27571 ],
      [ "NTF Lambert 2 Carto (27572)", 27572 ],
      [ "NTF Lambert 3 Carto (27573)", 27573 ],
      [ "NTF Lambert 4 Carto (27574)", 27574 ] ,
      [ "Réunion RGR92 - UTM 40S (2975)", 2975 ],
      [ "Antilles Françaises RRAF1991 - UTM 20N - IGN (4559)", 4559 ],
      [ "Guyane RGFG95 - UTM 22N (2972)", 2972 ],
      [ "Guyane RGFG95 - UTM 21N (3312)", 3312 ]
    ]
  end

  def projection_type_label
    self.class.available_srids.each do |a|
      if a.last.to_s == projection_type
        return a.first.split('(').first.rstrip
      end
    end
    projection_type || ""
  end

  after_create :create_schema
  def create_schema
    Apartment::Tenant.create "ch_#{self.id}"
  end

  def set_slug
    self.update_column(:slug, "ch_#{id}")
  end

  before_destroy :destroy_schema
  def destroy_schema
    Apartment::Tenant.drop "ch_#{self.id}"
  end

  before_destroy :destroy_jobs
  def destroy_jobs
    Ievkitdeprecated.delete_jobs("ch_#{self.id}")
    true
  end

  def upper_corner
    envelope.upper_corner
  end

  def upper_corner=(upper_corner)
    if String === upper_corner
      upper_corner = (upper_corner.blank? ? nil : GeoRuby::SimpleFeatures::Point::from_lat_lng(Geokit::LatLng.normalize(upper_corner), 4326))
    end

    envelope.tap do |envelope|
      envelope.upper_corner = upper_corner
      self.bounds = envelope.to_polygon.as_ewkt
    end
  end

  def lower_corner
    envelope.lower_corner
  end

  def lower_corner=(lower_corner)
    if String === lower_corner
      lower_corner = (lower_corner.blank? ? nil : GeoRuby::SimpleFeatures::Point::from_lat_lng(Geokit::LatLng.normalize(lower_corner), 4326))
    end

    envelope.tap do |envelope|
      envelope.lower_corner = lower_corner
      self.bounds = envelope.to_polygon.as_ewkt
    end
  end

  def default_bounds
    GeoRuby::SimpleFeatures::Envelope.from_coordinates( [ [-5.2, 42.25], [8.23, 51.1] ] ).to_polygon.as_ewkt
  end

  def envelope
    bounds = read_attribute(:bounds)
    GeoRuby::SimpleFeatures::Geometry.from_ewkt(bounds.present? ? bounds : default_bounds ).envelope
  end
end

app/controllers/referentials_controller.rb
class ReferentialsController < ChouetteController
  before_action :check_authorize, except: [:show, :index]
  skip_before_action :switch_referential
  defaults :resource_class => Referential

  respond_to :html
  respond_to :json, :only => :show
  respond_to :js, :only => :show

  def new
    new! do
      @referential.data_format = current_organisation.data_format
    end
  end

  def show
     resource.switch
     show! do |format|
       format.json {
         render :json => { :lines_count => resource.lines.count,
                :networks_count => resource.networks.count,
                :vehicle_journeys_count => resource.vehicle_journeys.count + resource.vehicle_journey_frequencies.count,
                :time_tables_count => resource.time_tables.count,
                :referential_id => resource.id}
       }
       format.html { build_breadcrumb :show}

     end
  end

  protected

  alias_method :referential, :resource

  def resource
    @referential ||= current_organisation.referentials.find_by_id(params[:id])
  end

  def collection
    @referentials ||= current_organisation.referentials.order(:name)
  end

  def build_resource
    super.tap do |referential|
      referential.user_id = current_user.id
      referential.user_name = current_user.name
    end
  end

  def create_resource(referential)
    referential.organisation = current_organisation
    super
  end

  private
  def referential_params
    params.require(:referential).permit( :id, :name, :prefix, :time_zone, :upper_corner, :lower_corner, :organisation_id, :projection_type, :data_format )
  end

end

app/helpers/referentials_helper.rb
module ReferentialsHelper
end

app/views/referentials/_clean.html.erb
  <div id="clean_up" >
  <%= semantic_form_for [@referential, CleanUp.new] do |form| %>
  <%= form.inputs do %> 
    <%= form.input :expected_date, :as => :date_picker , :wrapper_html => { :class => 'date', :title => t('titles.clean_up.expected_date') } %>
    <%= form.input :keep_lines, :as => :boolean %>
    <%= form.input :keep_stops, :as => :boolean %>
    <%= form.input :keep_companies, :as => :boolean %>
    <%= form.input :keep_networks, :as => :boolean %>
    <%= form.input :keep_group_of_lines, :as => :boolean %>
    <% end %>
    <%= form.actions do %>
      <%= form.action :submit, :as => :button, :label => t('clean_ups.actions.clean_up') , :button_html => {:data => {:confirm => t('clean_ups.actions.confirm') }}%>
    <% end %>
  <% end %>
  </div>

app/views/referentials/_counts.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><%= t(".objects") %></div>

  <ul class="list-group"  width="75%">
    <li class="list-group-item">
      <span class="badge"><%= @referential.networks.size %></span>
      <%= Referential.human_attribute_name("networks") %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @referential.companies.size %></span>
      <%= Referential.human_attribute_name("companies") %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @referential.group_of_lines.size %></span>
      <%= Referential.human_attribute_name("group_of_lines") %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @referential.lines.size %></span>
      <%= Referential.human_attribute_name("lines") %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @referential.vehicle_journeys.size %></span>
      <%= Referential.human_attribute_name("vehicle_journeys") %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @referential.time_tables.size %></span>
      <%= Referential.human_attribute_name("time_tables") %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @referential.connection_links.size %></span>
      <%= Referential.human_attribute_name("connection_links") %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @referential.route_sections.size %></span>
      <%= Referential.human_attribute_name("route_sections") %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @referential.stop_areas.size %></span>
      <%= Referential.human_attribute_name("stop_areas") %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @referential.stop_areas.where("area_type = ?","BoardingPosition").size %></span>
      <%= image_tag "map/boarding_position.png"%><%= Referential.human_attribute_name("boarding_positions") %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @referential.stop_areas.where("area_type = ?","Quay").size %></span>
      <%= image_tag "map/quay.png"%><%= Referential.human_attribute_name("quays") %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @referential.stop_areas.where("area_type = ?","CommercialStopPoint").size %></span>
      <%= image_tag "map/commercial_stop_point.png"%><%= Referential.human_attribute_name("commercial_stops") %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @referential.stop_areas.where("area_type = ?","StopPlace").size %></span>
      <%= image_tag "map/stop_place.png"%><%= Referential.human_attribute_name("stop_places") %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @referential.stop_areas.where("area_type = ?","ITL").size %></span>
      <%= image_tag "map/itl.png"%><%= Referential.human_attribute_name("itls") %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @referential.access_points.size %></span>
      <%= image_tag "map/access_in_out.png"%><%= Referential.human_attribute_name("access_points") %>
    </li>
  </ul>
</div>

app/views/referentials/_form.erb
<%= semantic_form_for @referential, :class => "form-horizontal" do |form| %>
  <%= form.inputs do %>
    <%= form.input :name %>
    <%= form.input :prefix, :input_html => { :title => t("formtastic.titles.referential.prefix")} %>
    <%= form.input :projection_type, :as => :select, :collection => Referential.available_srids %>
    <%= form.input :time_zone %>
    <%= form.input :upper_corner, :input_html => { :title => t("formtastic.titles.referential.upper_corner")} %>
    <%= form.input :lower_corner, :input_html => { :title => t("formtastic.titles.referential.lower_corner")} %>
    <%= form.input :data_format, :label => true, :include_blank => false %>
  <% end %>

  <%= form.actions do %>
    <%= form.action :submit, :as => :button %>
    <%= form.action :cancel, :as => :link %>
  <% end %>
<% end %>

app/views/referentials/_line.erb
<%= div_for(referential) do %>
  <%= link_to referential.name, referential %>
  <div class="info">

  </div>
<% end %>

app/views/referentials/_referential.erb
<div id="index_item" class="panel panel-default referential">
  <div class="panel-heading">
    <div class="panel-title clearfix">
      <% if policy(:application).write? %>
        <span class="pull-right">
          <%= link_to edit_referential_path(referential), :class => "btn btn-default btn-sm" do %>
            <span class="fa fa-pencil"></span>
          <% end %>
          <%= link_to referential_path(referential), :method => :delete, :data => {:confirm =>  t('referentials.actions.destroy_confirm')}, :class => "btn btn-danger btn-sm" do %>
            <span class="fa fa-trash-o"></span>
          <% end %>
        </span>
      <% end %>
      <h5>
        <%= link_to([@referential, referential], :class => "preview", :title => "#{Referential.model_name.human.capitalize} #{referential.name}") do %>
        <span class="name">
          <%= truncate(referential.name, :length => 20) %>
        </span>
        <% end %>
      </h5>
    </div>
  </div>
  <div id="referential_<%= referential.id %>" class="panel-body">
    <p>
      <%= referential.human_attribute_name('lines') %>: <span class="lines_count"></span>
    </p>
    <p>
      <%= referential.human_attribute_name('networks') %>: <span class="networks_count"></span>
    </p>
    <p>
      <%= referential.human_attribute_name('vehicle_journeys') %>: <span class="vehicle_journeys_count"></span>
    </p>
    <p>
      <%= referential.human_attribute_name('time_tables') %>: <span class="time_tables_count"></span>
    </p>
  </div>
</div>
<%= javascript_include_tag referential_path(referential,:format => :js) %>

app/views/referentials/_validity_out.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><%= t('.validity_out_time_tables') %>: <%= tm_cnt = @referential.time_tables.validity_out_from_on?(Date.today).size %></div>
  <ul class="list-group">
  	<% if tm_cnt > 0 %>
	  <% @referential.time_tables.validity_out_from_on?(Date.today,5).each do |tm| %>
	  <li class="list-group-item"><%= link_to tm.comment, referential_time_table_path(@referential, tm) %></li>
	  <% end %>
	  <% if tm_cnt > 5 %>
	  <li class="list-group-item">...</li>
    <% end %>
  	<% end %>
  </ul>
</div>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><%= t('.validity_out_soon_time_tables', :count => "7") %>: <%= tm_cnt = @referential.time_tables.validity_out_between?(Date.today,Date.today+7).size %></div>
  <ul class="list-group">
  	<% if tm_cnt > 0 %>
	  <% @referential.time_tables.validity_out_between?(Date.today,Date.today+7,5).each do |tm| %>
	  <li class="list-group-item"><%= link_to tm.comment, referential_time_table_path(@referential, tm) %></li>
	  <% end %>
	  <% if tm_cnt > 5 %>
	  <li class="list-group-item">...</li>
    <% end %>
  	<% end %>
  </ul>
</div>

app/views/referentials/edit.html.erb
<%= title_tag t(".title") %>

<%= render "form" %>

app/views/referentials/index.html.erb
<%= title_tag Referential.model_name.human(:count => 2) %> 

<div class="referentials paginated_content">
  <%= paginated_content @referentials %>
</div>

<% content_for :sidebar do %>
<ul class="actions">
  <li><%= link_to t('referentials.actions.new'), new_referential_path, :class => "add" %></li>
</ul>
<% end %>

app/views/referentials/new.html.erb
<%= title_tag t(".title") %>

<%= render "form" %>

app/views/referentials/show.html.erb
<%= title_tag @referential.name %>

<div class="summary">
  <p>
  <label><%= Referential.human_attribute_name("prefix") %>: </label>
  <%= @referential.prefix %>
  </p>
  <p>
  <label><%= Referential.human_attribute_name("projection_type") %>: </label>
  <% if ! @referential.projection_type_label.empty? %>
     <%= @referential.projection_type_label %> (epsg:<%= @referential.projection_type %>)
  <% end %>
  </p>
  <p>
  <label><%= Referential.human_attribute_name("time_zone").capitalize %>: </label>
  <%= @referential.time_zone_tzinfo %>
  </p>
  <p>
  <label><%= Referential.human_attribute_name("data_format_restrictions") %>: </label>
  <%= @referential.data_format %>
  </p>
  <p>
  	<label><%= Referential.human_attribute_name("validity_period") %>: </label>
  	<% if Chouette::TimeTable.start_validity_period.nil? %>
  	 <%= Referential.human_attribute_name("no_validity_period") %>
  	<% else %>
     <%= Referential.human_attribute_name("start_validity_period") %>
     <%= l Chouette::TimeTable.start_validity_period %>
     <%= Referential.human_attribute_name("end_validity_period") %>
     <%= l Chouette::TimeTable.end_validity_period %>
   <% end %>
  </p>

  <table width="100%">
  	<tr>
  	  <td valign="top" width="50%">
        <%= render "counts" %>
      </td>
      <td valign="top" >
        <%= render "validity_out" %>
      </td>
    </tr>
  </table>

  <% if @referential.api_keys.present? %>
  <h3 class="api_keys"><%= t('.api_keys') %></h3>
  <div class="api_keys paginated_content">
    <%= paginated_content(@referential.api_keys, "api_keys/api_key") %>
  </div>
  <% end %>
</div>

<% content_for :sidebar do %>
<ul class="actions">
  <li><%= link_to t('referentials.actions.edit'), edit_referential_path(@referential), :class => "edit" %></li>
  <li><%= link_to t('referentials.actions.destroy'), referential_path(@referential), :method => :delete, :data => {:confirm =>  t('referentials.actions.destroy_confirm')}, :class => "remove" %></li>
  <li><%= link_to t('api_keys.actions.new'), new_referential_api_key_path(@referential), :class => "add" %></li>
  <br>
</ul>

<h4><%= t('.clean_up') %></h4>
<%= render "clean" %>
<% end %>

app/views/referentials/show.js.erb
$(function (){
    var ref, update_infos, update_referential_details, _i, _len, _ref, _results;

    update_infos = function(json) {
        var info, update_info;
        info = $('#referential_' + json.referential_id);
        console.log(info)
        update_info = function(key, value) {
            if (key.match(/_count$/)) {
                return $(info.find('.' + key)[0]).text(value);
            }
        };
        return $.each(json, update_info);
    };
    
    update_referential_details = function() {
        return $.getJSON("<%= referential_path(@referential, :format => :json) %>", update_infos);
    };

    _results = [];
    _results.push(update_referential_details());

    return _results; 
});